### PR TITLE
Add pre-commit

### LINKED ISSUE #13: add `pre-commit`
I would like to add a `.pre-commit-config.yaml` file to the repo. This way we can have code linting and formatting done on any code that is submitted.

This will require changes to the repo, as there are several files that will need to be updated if we implement it.

### PR DESCRIPTION
**Pull request by ndmlny-qs**
- Adding `pre-commit` to the repository. The new `pre-commit` directives can be found in the configuration file `.pre-commit-config.yaml`.
- Removed excess ignore items in the `.gitignore` for simplicity.
- Added `.taplo.toml` to enforce TOML file formatting.
- Updated the readme for the new pre-commit hooks.
- Updated the pyproject.toml file with pre-commit configuration, as well as removing the tools handled by pre-commit from the dev install directive.

Resolves #13

### CODE REVIEW

**Comment by ndmlny-qs** [comment]
Note that none of these hooks have been run on the codebase yet. That will be done in the issue #20

**Review by aloctavodia — COMMENTED** [review]
We talked about adding an option to check for "print". Other than that LGTM.

**Comment by ndmlny-qs** [comment]
thanks for the reminder, I'll update for that as well

**Comment by ndmlny-qs** [comment]
I left it as a flake8 error when prints are found. I think blindly removing print statements is not the greatest of dev experiences, as it removes the opportunity to convert them to a log.

We should discuss adding checks for `TODO` or `FIXME` flags that may occur as well in a future PR.

**Review by aloctavodia — APPROVED** [review]

**Review by yilinxia — APPROVED** [review]
I noticed that we have two license files, is that intentional? otherwise, LGTM

**Comment by ndmlny-qs** [comment]
good catch, made an issue to remove it #22

**Pull request merged**
